name: Build and deploy package

on:
  push:
    branches:
      - main # --> Significa que os deploys ocorreram ao ter algum push na branch main (PR, etc)

# Falando que será subida uma máquina ubuntu pra gerar o build e deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

# Passos a serem executados:

    steps:
    - uses: actions/checkout@main # fazer um checkout da branch main

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # instalando sdk do dotnet
    
    - name: Build with dotnet # buildando a aplicação
      run: dotnet build --configuration Release

    - name: Test application # rodar test da aplicação
      run: dotnet test

    - name: Create the Package # criando pacote
      run: dotnet pack --configuration Release